coverage:
  range: 80..100
  status:
    project:
      default: off
      components:
        flags: components

# adding Flags to your `layout` configuration to show up in the PR comment
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

flags:
  components:
    paths:
      - lib/components/
      - "!lib/components/common/"
