# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Codecov

on:
  workflow_dispatch:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Flutter action
        # You may pin to the exact commit or the version.
        # uses: subosito/flutter-action@26bf50084a0c218b5b715a3641c36eac84fd2136
        uses: subosito/flutter-action@v1.4.0
        with:
          # The Flutter version to make available on the path
          flutter-version: "2.x" # optional
          # The Flutter build release channel
          channel: "stable" # optional, default is stable

      # 下载项目依赖
      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      # 执行测试
      - name: Run tests
        run: flutter test --coverage --coverage-path coverage/lcov.info

      - name: clean untested file
        run: flutter pub active clean_coverage && \
             flutter  pub global run clean_coverage clean --exclusions-file codecov_exclusions.txt coverage/lcov.info

      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
