# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: publish_dry

on:
  workflow_dispatch:
  # push:
  #   branches: [master]
  # pull_request:
  #   branches: [master]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Flutter action
        # You may pin to the exact commit or the version.
        # uses: subosito/flutter-action@26bf50084a0c218b5b715a3641c36eac84fd2136
        uses: subosito/flutter-action@v1.4.0
        with:
          # The Flutter version to make available on the path
          flutter-version: "2.x" # optional
          # The Flutter build release channel
          channel: "stable" # optional, default is stable

      # 下载项目依赖
      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      # 执行测试
      - name: Run tests
        run: flutter test

      - name: Publish Dart/Flutter package
        # You may pin to the exact commit or the version.
        # uses: sakebook/actions-flutter-pub-publisher@7112915a1a834881d4c98ef7af12f3456e5c79c7
        uses: sakebook/actions-flutter-pub-publisher@v1.3.1
        with:
          # Google Account credential
          credential: ${{ secrets.CREDENTIAL_JSON }}
          # (Optional) Publish packages type. (default: true)
          flutter_package: true # optional, default is true
          # (Optional) Skip test (default: false)
          skip_test: true # optional
          # (Optional) Dry run, no publish (default: false)
          dry_run: true # optional

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          # A personal access token for the GitHub repository in which the release will be created and edited.
          # It is recommended to create the access token with the following scopes: `repo, user, admin:repo_hook`.
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: CHANGELOG.md
          tag: ${{ github.ref }}
